### ISSUE TITLE
Add link to contract principal

### ISSUE THREAD

**Issue by edu-stx** [hirosystems/btcweb3#14]
See https://github.com/hirosystems/stacking/pull/7#issuecomment-1408661276

**Comment by friedger** [comment]
fixed in 81772bf1c9e0434e3e33dde3f40ab7bc88c38458

**Comment by friedger** [comment]
completed by [5d7ea54](https://github.com/hirosystems/btcweb3/commit/5d7ea5418b43b1a0eb5aa642f5b73c95ad65076b)
