### ISSUE TITLE
Add stack-extend support for Stacking

### ISSUE THREAD

**Issue by markmhx** [hirosystems/btcweb3#2]
Empowering users to extend their current Stacking commitment by more cycles instead of incurring a "cooldown cycle" at the end it, in which they lose the chance to earn more BTC for one cycle.

See https://github.com/stacks-network/stacks-blockchain/pull/3318

This should include removing references to the cooldown cycle throughout the UI. E.g.

<img width="626" alt="image" src="https://user-images.githubusercontent.com/28991/201142851-b6fb3bb6-090f-493c-9a61-facdb3a25ec0.png">

**Comment by mica000** [comment]
**Stacking by yourself:**

[Prototype](https://www.figma.com/proto/VcXbxT1EwXvE1nUlOiBEES/Wallet-(%F0%9F%92%BF-desktop)?page-id=6818%3A40809&node-id=7014%3A83392&viewport=1444%2C1287%2C0.31&scaling=min-zoom&starting-point-node-id=7014%3A83392&show-proto-sidebar=1)

[Figma] https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet-(%F0%9F%92%BF-desktop)?node-id=7014%3A83408&t=00gkXe2qCqElxgyq-4

[PoX2 components](https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet-(%F0%9F%92%BF-desktop)?node-id=7069%3A125901&t=hD5pa3G33nvKyIVI-4)
