### ISSUE TITLE
Prefill btc address from user account in start direct stacking

### ISSUE THREAD

**Issue by friedger** [hirosystems/btcweb3#21]
Similar to start pooling, the btc address field can be prefilled with the btc address coming from the wallet

![image](https://user-images.githubusercontent.com/1449049/227506691-86e6b9d5-8b92-48e9-ba02-5f08c7947519.png)

**Comment by friedger** [comment]
This is how it looks on pooled stacking
![image](https://user-images.githubusercontent.com/1449049/227506973-621ab033-3cce-4101-9af9-a42f371df7fa.png)

**Comment by friedger** [comment]
A side note, testnet addresses are rejected in direct stacking

**Comment by mica000** [comment]
> Similar to start pooling, the btc address field can be prefilled with the btc address coming from the wallet
> 
> ![image](https://user-images.githubusercontent.com/1449049/227506691-86e6b9d5-8b92-48e9-ba02-5f08c7947519.png)

Yes! This would be great if it can be pre-filled

**Comment by mica000** [comment]
> A side note, my address tb1qtu8aq680jkn7v55y4fuz0ujrrlye89aka208he was rejected in direct stacking



> A side note, my address tb1qtu8aq680jkn7v55y4fuz0ujrrlye89aka208he was rejected in direct stacking

Do we know the reason why?

**Comment by friedger** [comment]
There was an issue with the logic.

Fixed in d2239acaac6bf1a839311f0829c47362d5995cf6
