### ISSUE TITLE
Incorrect state after direct stacking ended

### ISSUE THREAD

**Issue by friedger** [hirosystems/btcweb3#23]
I stacked for 12 cycles. The 12 cycles passed and I see the status below:

![image](https://user-images.githubusercontent.com/1449049/227509392-07f606d8-07a4-4e12-9ad8-ab46037d6ac6.png)

**Comment by markmhx** [comment]
Should we closed as resolved given the above commit?

**Comment by friedger** [comment]
The comment used a wrong issue number

**Comment by markmhx** [comment]
This still needs resolution then? Want to take it or best for Edu?

**Comment by friedger** [comment]
I am working on it

**Comment by friedger** [comment]
Addressed in d49c6575baf94c9538aa603d12298286c0d1b070
