### ISSUE TITLE
Add Bitcoin address support for Native SegWit and Taproot for Stacking

### ISSUE THREAD

**Issue by markmhx** [hirosystems/btcweb3#3]
Per https://stacks.org/stacks-21-what-to-expect

> Stacks 2.1 adds support for Stacking to a native segwit or taproot address. This not only saves users Bitcoin transaction fees, but also enables a greater degree of programmatic control over the accumulated Bitcoin by means of tapscripts. For example, it would now be possible to build a decentralized Stacking pool that pays BTC by crafting a tapscript to ensure that each participant receives only their fair share of the reward.

<img width="644" alt="image" src="https://user-images.githubusercontent.com/28991/201141444-63561b1a-3dea-4643-b221-63d33ef4f013.png">

[See Figma](https://www.figma.com/file/IL0lo9eshXEaQ0SfpwreYh/Wallet-(%F0%9F%92%BF-desktop)-(Stacks-2.1)?node-id=4998%3A34141)

**Comment by markmhx** [comment]
This is tackled now in the desktop wallet but needs implementation in the Stacking app.

**Comment by markmhx** [comment]
@edu-stx to add a PoX2 activation check for this functionally

**Comment by friedger** [comment]
This is also used for Pooled Stacking for the users btc address.

**Comment by markmhx** [comment]
@friedger let's create a separate issue if we want to collect BTC reward addresses in the pooling form specifically

**Comment by friedger** [comment]
@markmhx It is part of issue https://github.com/hirosystems/btcweb3/issues/17

**Comment by friedger** [comment]
Addressed in d2239acaac6bf1a839311f0829c47362d5995cf6.
