### ISSUE TITLE
Add stack-increase support for Stacking

### ISSUE THREAD

**Issue by markmhx** [hirosystems/btcweb3#4]
Empowering users to increase the amount of STX locked for an existing Stacking commitment instead of waiting for the remaining cycles to pass and their currently locked STX to unlock first.

See https://github.com/stacks-network/stacks-blockchain/pull/3318

**Comment by mica000** [comment]
https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet-(%F0%9F%92%BF-desktop)-%E2%80%94-Michelly's-file?node-id=7014%3A83811&t=iCyEm8i3C1svys1c-4
