### ISSUE TITLE
Add network indicator

### ISSUE THREAD

**Issue by friedger** [hirosystems/btcweb3#42]
It is not clear whether which network is currently used

**Comment by markmhx** [comment]
Let's do something really lowfi design wise / no need to create a complicated button. Maybe just a toggle in the footer?

**Comment by mica000** [comment]
Design ready: https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet-(%F0%9F%92%BF-desktop)?node-id=6885-56480&t=egvkfUsIrO1WgMtU-4
