### ISSUE TITLE
Improve lateral margins for Stacking choice areas on home

### ISSUE THREAD

**Issue by markmhx** [hirosystems/btcweb3#51]
Right now the left-side gets a lot smaller than the right-side on common viewports

<img width="1162" alt="Screenshot 2023-03-28 at 12 51 10" src="https://user-images.githubusercontent.com/28991/228216262-a3232b2f-51ac-4908-aecf-4570d771c500.png">

**Comment by friedger** [comment]
fixed by https://github.com/hirosystems/btcweb3/pull/89/commits/02b1522952d5d2ca96e8dafbac024d254986093f

![image](https://user-images.githubusercontent.com/1449049/230316995-da198197-3eab-4fb6-b58f-11c5e0e43aec.png)
