### ISSUE TITLE
Improve FAQ link in homepage banner

### ISSUE THREAD

**Issue by markmhx** [hirosystems/btcweb3#53]
It should go to https://wallet.hiro.so/wallet/faq#stacking (note anchor tag at end)

<img width="1414" alt="Screenshot 2023-03-28 at 13 27 03" src="https://user-images.githubusercontent.com/28991/228221931-be59b9fa-145b-4e0a-9ef8-296d2d487f95.png">

**Comment by edu-stx** [comment]
ok, on it
