### ISSUE TITLE
Add margin between help icons and info values on right-hand side of form

### ISSUE THREAD

**Issue by markmhx** [hirosystems/btcweb3#54]
<img width="462" alt="Screenshot 2023-03-28 at 13 29 17" src="https://user-images.githubusercontent.com/28991/228222458-2df36809-631c-492a-b410-530603c957ff.png">

**Comment by friedger** [comment]
fixed by https://github.com/hirosystems/btcweb3/commit/1f557635332e53723a207c0af4c593c618906bcc
