### ISSUE TITLE
Hide "Reward address" section entirely when the user selects custom pool

### ISSUE THREAD

**Issue by markmhx** [hirosystems/btcweb3#58]
Right now the field disappears but the header and description for the section still remain:

<img width="745" alt="Screenshot 2023-03-28 at 13 33 42" src="https://user-images.githubusercontent.com/28991/228223505-1a186cda-b0bd-4ce7-8fd5-49d307eafe0a.png">

**Comment by friedger** [comment]
The current "Reward address" section is a fix of #44
