### ISSUE TITLE
UI + copy Improvement to choosing a duration step — Stacking in a pool

### ISSUE THREAD

**Issue by mica000** [hirosystems/btcweb3#6]
When pooling a user has to choose a duration on which they can opt between Limited and Indefinite however it's believed that this might be causing more confusion than bringing value. 

On the current implementation, it's counterintuitive that users would choose Indefinite permission for a few reasons:
1. It gives them less control of their STXs and no guarantee of when they would be available;
2. Currently by default the form chooses limited, being Indefinite left as the second option;
3. Lacks information about when their STXs would be unlocked and what to consider.

----

So I'm suggesting a few improvements and I would like to know whether you think it makes sense to:
1. Copy to include more details about how unlocking works for Indefinite permission;
2. A component that would act as an explainer of the use case or benefit: Recommended for... (Content needs to be defined)
3. Swap the order between components, making "Indefinite Permission" a priority;

[Figma file](https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet-(%F0%9F%92%BF-desktop)?node-id=7330%3A116376&t=j9TQs5zs5iOj6KrF-4)

<img width="1108" alt="Screenshot 2023-01-12 at 21 26 24" src="https://user-images.githubusercontent.com/119523541/212173811-f6878b2a-4613-46fe-aaa7-8d9aeb0f4f2f.png">

**Comment by kyranjamie** [comment]
Agree with your suggestions @mica000 

Suggest copy explains along the lines of:
- **Indefinitely**: Recommended for users who wish to stack continuously and, when wishing to access STX again, understand revocation must be done before funds are re-stacked by pool.
- **Limited**: Recommend for users who want to guarantee funds are not locked beyond a certain period.

**Comment by markmhx** [comment]
+1 on this set of improvements

For the "limited" copy, we may also want to note that users who select it will need to come back and re-pool if they want to continue stacking past the limit.

**Comment by friedger** [comment]
Has been released

![image](https://user-images.githubusercontent.com/1449049/230070540-8120ba72-8728-4ecf-a352-671df2c0a0e5.png)
