### ISSUE TITLE
Generalize app nav and repo name

### ISSUE THREAD

**Issue by markmhx** [hirosystems/btcweb3#8]
To include other functionality aside from Stacking, namely NFTs to start

**Comment by markmhx** [comment]
Looks good! Though let's capitalize "Web3" for "Bitcoin Web3"?

**Comment by mica000** [comment]
![Image](https://user-images.githubusercontent.com/119523541/219374321-4aa95dbd-2526-4747-a3cb-56b69f5c057f.svg)
